# This is a basic workflow to help you get started with Actions

name: Mirror GitHub Auto Queried Repos to Gitee

on:
  push:
    branches: [ main ]
    
  schedule:
    - cron: '0 17 * * *'
    
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest

    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/halo-sigs
        dst: gitee/halo-sigs
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        account_type: org
        black_list: '.github'
